/*
 * saveYesNo.java
 *
 * Created on December 28, 2002, 11:02 AM
 */
import com.likha.license.*;
/**
 *
 * @author  test1
 */
public class activateLicense extends javax.swing.JDialog {
    
    License lic = new License();
    
    /** Creates new form saveYesNo */
    public activateLicense(mainForm parent, boolean modal) {
        super(parent, modal);
        initComponents();        
        main = parent;        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        activateButton = new javax.swing.JButton();
        licenseTextField = new javax.swing.JTextField();

        setTitle("License Key");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Default", 0, 11));
        jLabel1.setText("License Key:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        activateButton.setFont(new java.awt.Font("Default", 0, 11));
        activateButton.setText("Activate");
        activateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(25, 5, 5, 5);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(activateButton, gridBagConstraints);

        licenseTextField.setMinimumSize(new java.awt.Dimension(100, 21));
        licenseTextField.setPreferredSize(new java.awt.Dimension(300, 21));
        jPanel1.add(licenseTextField, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-447)/2, (screenSize.height-172)/2, 447, 172);
    }//GEN-END:initComponents

    private void activateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateButtonActionPerformed
        // Add your handling code here:
        String key = licenseTextField.getText().trim();
        if( key.length() < 33 ) {
            main.printMessage( "Invalid License Key.  Please re-enter key." );
        } else {
            if( lic.writePaidLicense( key ) ) {
                setVisible(false);
                dispose();
                main.printMessage( "License Key accepted." );
                main.printMessage( "Thanks for purchasing DevCentre IDE." );
                main.printMessage( "Please relaunch DevCentre IDE." );
            } else {
                main.printMessage( "Invalid License Key.  Please re-enter key." );
            }
            
        }
        
    }//GEN-LAST:event_activateButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
       
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //new saveYesNo( mainForm parent, true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField licenseTextField;
    // End of variables declaration//GEN-END:variables
    
    private mainForm main;
}
